name: 'Deploy a Wordpress VM to Azure action - Quickstart Template'
description: 'This action helps create an Azure VM and deploy Wordpress on it'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to login to azure'
    required: true
  tenant-id:
    description: 'Tenant id to login to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  admin-username:
    description: 'Admin username to login to app'
    required: true
  admin-password:
    description: 'Admin password to login to app and mySql'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3
      
    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: true

    - name: 'Az deploy - Wordpress on VM'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ inputs.subscription-id }}
        resourceGroupName: ${{ inputs.resource-group-name }}
        template: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/application-workloads/wordpress/wordpress-single-vm-ubuntu/azuredeploy.json
        parameters: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/application-workloads/wordpress/wordpress-single-vm-ubuntu/azuredeploy.parameters.json
                    authenticationType=password
                    mySqlPassword=${{ inputs.admin-password }}
                    vmDnsName=dns-vm-2
                    vmSize=Standard_D2as_v4
                    adminUsername=${{ inputs.admin-username }}
                    adminPasswordOrKey=${{inputs.admin-password}}
        failOnStdErr: false
      
    - name: Fetch deployment record - Run Azure PowerShell inline script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzResourceGroupDeploymentOperation -ResourceGroupName ${{ inputs.resource-group-name }} -DeploymentName "azuredeploy"
        azPSVersion: "latest"
