name: 'Deploy a Wordpress VM to Azure action - Custom Template'
description: 'This action helps create an Azure VM and deploy Wordpress on it'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to login to azure'
    required: true
  tenant-id:
    description: 'Tenant id to login to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  admin-username:
    description: 'Admin username to login to vm'
    required: true
  admin-password:
    description: 'Admin password to login to vm'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3
      
    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: false

    - name: 'Accept Bitnami marketplace terms'
      shell: bash
      run: |
        az vm image terms accept --urn bitnami:wordpress:4-4:latest
        
    - name: 'Az deploy - Wordpress on VM Bitnami'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ inputs.subscription-id }}
        resourceGroupName: ${{ inputs.resource-group-name }}
        template: https://raw.githubusercontent.com/vaibbavisk20/deploy_wordpress_vm_azure/main/vm_template.json
        parameters: https://raw.githubusercontent.com/vaibbavisk20/deploy_wordpress_vm_azure/main/vm_parameters.json
                    adminUsername=${{ inputs.admin-username }}
                    adminPassword=${{ inputs.admin-password }}
        failOnStdErr: false

    # - name: 'Az deploy - LAMP on VM Bitnami'
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ inputs.subscription-id }}
    #     resourceGroupName: ${{ inputs.resource-group-name }}
    #     template: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/application-workloads/wordpress/wordpress-single-vm-ubuntu/azuredeploy.json
    #     parameters: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/application-workloads/wordpress/wordpress-single-vm-ubuntu/azuredeploy.parameters.json
    #                 mySqlPassword=${{ inputs.admin-password }}
    #                 adminPasswordOrKey=${{ inputs.admin-password }}
    #                 vmDnsName='wordpress-dns-t1'
    #                 adminUsername=${{inputs.admin-username}}
    #     failOnStdErr: false

    - name: Fetch JSON file from remote repository
      shell: bash
      run: |
        json_url="https://raw.githubusercontent.com/vaibbavisk20/deploy_wordpress_vm_azure/main/vm_parameters.json"
        curl -sSLO $json_url

    - name: Print parameter value
      shell: bash
      run: |
        json_file="vm_parameters.json"
        # vm name
        virtual_machine_name=".parameters.virtualMachineName.value"
        result=$(jq -r "$virtual_machine_name" "$json_file")
        echo "Virtual Machine Properties"
        echo "Name: $result"

        # region
        location=".parameters.location.value"
        result=$(jq -r "$location" "$json_file")
        echo "Location: $result"

        # vm size
        virtual_machine_size=".parameters.virtualMachineSize.value"
        result=$(jq -r "$virtual_machine_size" "$json_file")
        echo "VM Size: $result"
